import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import {
  FaPhoneAlt,
  FaEnvelope,
  FaUser,
  FaBuilding,
  FaCalculator,
  FaAt,
  FaMapMarkerAlt,
  FaClock,
} from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CASA DI RIPOSO MONUMENTO AI CADUTI IN GUERRA (VE)",
  description: "Generated by create next app",
};

// Dati del footer
const footerData = {
  title: "Contatti",
  subtitle: "Siamo qui per aiutarti. Contattaci per qualsiasi informazione o supporto di cui hai bisogno.",
  contactItems: [
    {
      icon: FaPhoneAlt,
      title: "Telefono",
      content: "0421 330807",
      description: "Chiamaci per informazioni",
      isLink: false,
    },
    {
      icon: FaEnvelope,
      title: "Protocollo",
      content: "info@cdrmonumento.com",
      description: "Email principale",
      isLink: true,
      href: "mailto:info@cdrmonumento.com",
    },
    {
      icon: FaUser,
      title: "Presidenza",
      content: "presidente@cdrmonumento.com",
      description: "Contatto diretto",
      isLink: true,
      href: "mailto:presidente@cdrmonumento.com",
    },
    {
      icon: FaBuilding,
      title: "Direzione",
      content: "direttore@cdrmonumento.com",
      description: "Direzione generale",
      isLink: true,
      href: "mailto:direttore@cdrmonumento.com",
    },
    {
      icon: FaCalculator,
      title: "Contabilità e Rette",
      content: "contabilita@cdrmonumento.com",
      description: "Servizi amministrativi",
      isLink: true,
      href: "mailto:contabilita@cdrmonumento.com",
    },
    {
      icon: FaAt,
      title: "PEC",
      content: "cdrmonumento@halleypec.it",
      description: "Posta elettronica certificata",
      isLink: true,
      href: "mailto:cdrmonumento@halleypec.it",
    },
  ],
  copyright: {
    company: "Halley Informatica",
    year: "2025",
    piva: "Halley EG 041433",
  },
  badges: [
    {
      src: "https://www.cdrmonumento.com/immagini/yellow_wai-aa.gif",
      alt: "Icona di conformità di livello doppia A",
    },
    {
      src: "https://www.cdrmonumento.com/immagini/valid_html5.png",
      alt: "Icona di validità HTML5",
    },
    {
      src: "https://www.cdrmonumento.com/immagini/valid_css3.png",
      alt: "Icona di validità CSS3",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar
          logo={{
            src: "https://www.maalox.com/dam/jcr:554bf42e-c7fb-4bd0-8352-80bbb7a27ced/Logo.svg",
            alt: "Maalox Logo",
          }}
          menuItems={[
            { label: "Homepage", href: "/", active: true },
            {
              label: "SERVIZI",
              href: "#",
              dropdown: true,
              dropdownKey: "servizi",
            },
            {
              label: "PERCHE' L'IPAB",
              href: "#",
              dropdown: true,
              dropdownKey: "percheIpab",
            },
            {
              label: "I.P.A.B. informa",
              href: "#",
              dropdown: true,
              dropdownKey: "ipabInforma",
            },
            {
              label: "Accessi riservati",
              href: "#",
              dropdown: true,
              dropdownKey: "accessiRiservati",
            },
            { label: "Extranet", href: "/extranet" },
            { label: "PRIVACY", href: "/privacy" },
          ]}
          menuDropdowns={{
            servizi: {
              links: [
                {
                  label: 'CENTRO DIURNO "ANCHISE"',
                  href: "/centro-diurno-anchise",
                },
                {
                  label: 'CENTRO ANZIANI "COLORA IL TUO TEMPO"',
                  href: "/centro-anziani",
                },
                {
                  label: "SERVIZIO ASSISTENZA DOMICILIARE S.A.D.",
                  href: "/servizio-assistenza",
                },
                {
                  label: "SPORTELLO ASSISTENTI FAMILIARI",
                  href: "/sportello-assistenti-familiari",
                },
                {
                  label: 'PUNTO PRELIEVI "PASSARELLA" SERVIZIO INFERMIERISTICO',
                  href: "/punto-prelievi",
                },
              ],
            },
            percheIpab: {
              links: [
                { label: "VISION E MISSION", href: "/vision-mission" },
                {
                  label: "STATUTO",
                  href: "https://www.cdrmonumento.com/ae2131/zf/index.php/servizi-aggiuntivi/index/index/idtesto/20",
                },
              ],
            },
            ipabInforma: {
              title: "ACCESSO AGLI ATTI",
              description: [
                "Il servizio consente la consultazione degli atti amministrativi in corso di pubblicazione all'Albo Pretorio on-line, nonché degli atti la cui pubblicazione è scaduta.",
              ],
              links: [
                { label: "Albo pretorio", href: "/albo-pretorio" },
                { label: "Delibere", href: "/delibere" },
                { label: "Determine", href: "/determine" },
              ],
              right: {
                title: "AMMINISTRAZIONE TRASPARENTE",
                text: "In questa sezione sono pubblicati, raggruppati secondo le indicazioni di legge, documenti, informazioni e dati concernenti l'organizzazione dell'amministrazione, le attivita' e le sue modalita' di realizzazione.",
                links: [
                  {
                    label: "Amministrazione trasparente",
                    href: "/amministrazione-trasparente",
                  },
                ],
              },
            },
            accessiRiservati: {
              links: [
                { label: "Intranet sito", href: "/intranet-sito" },
                { label: "Area Dipendenti", href: "/" },
              ],
            },
            privacy: {
              links: [{ label: "Privacy Policy", href: "#" }],
            },
          }}
        />

        {children}
        <Footer data={footerData} />
      </body>
    </html>
  );
}
