import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CASA DI RIPOSO MONUMENTO AI CADUTI IN GUERRA (VE)",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar
          logo={{
            src: "https://www.maalox.com/dam/jcr:554bf42e-c7fb-4bd0-8352-80bbb7a27ced/Logo.svg",
            alt: "Maalox Logo",
          }}
          menuItems={[
            { label: "Homepage", href: "/", active: true },
            {
              label: "SERVIZI",
              href: "#",
              dropdown: true,
              dropdownKey: "servizi",
            },
            {
              label: "PERCHE' L'IPAB",
              href: "#",
              dropdown: true,
              dropdownKey: "percheIpab",
            },
            {
              label: "I.P.A.B. informa",
              href: "#",
              dropdown: true,
              dropdownKey: "ipabInforma",
            },
            { label: "Sostienici", href: "/" },
            {
              label: "Accessi riservati",
              href: "#",
              dropdown: true,
              dropdownKey: "accessiRiservati",
            },
            { label: "Extranet", href: "/extranet" },
            { label: "PRIVACY", href: "/privacy" },
          ]}
          menuDropdowns={{
            servizi: {
              links: [
                {
                  label: 'CENTRO DIURNO "ANCHISE"',
                  href: "/centro-diurno-anchise",
                },
                {
                  label: 'CENTRO ANZIANI "COLORA IL TUO TEMPO"',
                  href: "/centro-anziani",
                },
                {
                  label: "SERVIZIO ASSISTENZA DOMICILIARE S.A.D.",
                  href: "/servizio-assistenza",
                },
                {
                  label: "SPORTELLO ASSISTENTI FAMILIARI",
                  href: "/sportello-assistenti-familiari",
                },
                {
                  label: 'PUNTO PRELIEVI "PASSARELLA" SERVIZIO INFERMIERISTICO',
                  href: "/punto-prelievi",
                },
              ],
            },
            percheIpab: {
              links: [
                { label: "VISION E MISSION", href: "/vision-mission" },
                {
                  label: "STATUTO",
                  href: "https://www.cdrmonumento.com/ae2131/zf/index.php/servizi-aggiuntivi/index/index/idtesto/20",
                },
              ],
            },
            ipabInforma: {
              title: "ACCESSO AGLI ATTI",
              description: [
                "Il servizio consente la consultazione degli atti amministrativi in corso di pubblicazione all'Albo Pretorio on-line, nonché degli atti la cui pubblicazione è scaduta.",
              ],
              links: [
                { label: "Albo pretorio", href: "/albo-pretorio" },
                { label: "Delibere", href: "/delibere" },
                { label: "Determine", href: "/determine" },
              ],
              right: {
                title: "AMMINISTRAZIONE TRASPARENTE",
                text: "In questa sezione sono pubblicati, raggruppati secondo le indicazioni di legge, documenti, informazioni e dati concernenti l'organizzazione dell'amministrazione, le attivita' e le sue modalita' di realizzazione.",
                links: [
                  {
                    label: "Amministrazione trasparente",
                    href: "/amministrazione-trasparente",
                  },
                ],
              },
            },
            accessiRiservati: {
              links: [
                { label: "Intranet sito", href: "/intranet-sito" },
                { label: "Area Dipendenti", href: "/" },
              ],
            },
            privacy: {
              links: [{ label: "Privacy Policy", href: "#" }],
            },
          }}
        />

        {children}
        <Footer />
      </body>
    </html>
  );
}
